# Generated by Django 2.1.1 on 2018-09-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20180908_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='status',
            field=models.IntegerField(choices=[(1, 'todo'), (2, 'progress'), (3, 'onhold'), (4, 'done')], default=1),
        ),
    ]
